apiVersion: apps/v1
kind: Deployment
metadata:
  name: fittrack-mysql
  namespace: fittrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fittrack-mysql
  template:
    metadata:
      labels:
        app: fittrack-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Likhi@33459" # your MySQL password
            - name: MYSQL_DATABASE
              value: "fittrack"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {} # demo only (data lost if pod deleted)

---
apiVersion: v1
kind: Service
metadata:
  name: fittrack-mysql
  namespace: fittrack
spec:
  selector:
    app: fittrack-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
