apiVersion: apps/v1
kind: Deployment
metadata:
  name: fittrack-frontend
  namespace: fittrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fittrack-frontend
  template:
    metadata:
      labels:
        app: fittrack-frontend
    spec:
      containers:
        - name: frontend
          image: likhithachundu/fittrack-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fittrack-frontend
  namespace: fittrack
spec:
  selector:
    app: fittrack-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
